version: "3.9"
services:
    api:
      build: ./api
      ports: 
        - "5000:5000"
      volumes:
        - ./api/src:/app/src
    
    web:
      build: ./client
      environment:
        - CI=true
      ports: 
        - "3000:3000"
      volumes: 
        - ./client/src:/app/src
        - ./client/public:/app/public